# Generated by Django 4.2.27 on 2025-12-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_moverequest_status_moverequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='moverequest',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='moverequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
